jenkins:
  systemMessage: "Jenkins Job Setup"

unclassified:
  location:
    url: "https://jenkins.skynetx.me"

jobs:
  - file: "/usr/local/webhook.groovy"
  - file: "/usr/local/helm-cve-status-check.groovy"
  - file: "/usr/local/helm-cve-release.groovy"
